//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class sinavSonuclari
    {
        public System.DateTime sinavTarih { get; set; }
        public int okulNo { get; set; }
        public int soruSayisi { get; set; }
        public int dogruSayisi { get; set; }
        public int yanlisSayisi { get; set; }
        public string dogruYapilanSorular { get; set; }
        public string yanlisYapilanSorular { get; set; }
    }
}
