//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sinav
    {
        public string sinavID { get; set; }
        public string soruIDler { get; set; }
        public int soruSayisi { get; set; }
        public int sinavSuresi { get; set; }
    }
}
