//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soru
    {
        public int soruID { get; set; }
        public string soruMetin { get; set; }
        public int soruUnite { get; set; }
        public int soruKonu { get; set; }
        public string dogruCevap { get; set; }
        public string yanlisCevap1 { get; set; }
        public string yanlisCevap2 { get; set; }
        public string yanlisCevap3 { get; set; }
        public byte[] resim { get; set; }
    }
}
